# Open shell with '!'
[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# Enter directory or open file with 'l'
[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# Enter directory or open file with '<Enter>'
[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

# Paste into hovered directory with 'p'
[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin --sync smart-paste"
desc = "Paste into the hovered directory or CWD"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
